name: "Check PR Spell"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  console:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "$GITHUB_CONTEXT"
